#!/bin/sh

# start the squishserver
squishserver &

# create a dated filename for the logfile
USER_HOME=$(eval echo ~${SUDO_USER})
TIMESTAMP=`date +%Y%m%d%H%M`
RESULTFOLDER=$USER_HOME/squish-results/$TIMESTAMP
SUITEFOLDER=$USER_HOME/tooling_auto/suite_CascadesBuilder_sanity
mkdir -p $RESULTFOLDER


RESULTFILE=$RESULTFOLDER/result.xml
GTESTRESULTFILE=$RESULTFOLDER/gtestresult.xml
EMAILIDS=aaa


unamestr=`uname`

if [ "$unamestr" = 'Darwin' ]; then
 sed  's/AUT=qde/AUT=Momentics/g'  $SUITEFOLDER/suite.conf  > tmp
 mv tmp $SUITEFOLDER/suite.conf
fi




# execute the test
squishrunner --testsuite $SUITEFOLDER    --testcase tst_Components_view  --testcase tst_Outline_view --testcase tst_Properties_view \
			        	 --testcase tst_Release \
					 --testcase tst_Debug_Qml \
					 --testcase tst_Debug_Js \
					 --testcase tst_Debug_Native \
					 --testcase tst_Debug_PrettyPrinting \
					 --testcase tst_Debug_Qtypes \
					 --testcase tst_Debug_Redebug \
					 --testcase tst_CS4_Profile \
					 --testcase tst_CS4_ReProfile \
					 --testcase tst_Template_Projects \
					 --reportgen xmljunit,$RESULTFILE --resultdir $RESULTFOLDER


# stop the squishserver
squishserver --stop


python parse.py  -i $RESULTFILE  -o $GTESTRESULTFILE -e $EMAILIDS -t $TIMESTAMP

